package me.legrange.panstamp;

/**
 * An event generated by an endpoint. 
 * 
 * @author gideon
 * @param <T> The type of the data produced and consumed by the endpoint.
 */
public interface EndpointEvent<T> {
    
    /**  The possible types of events that can be received for an endpoint. */
    public enum Type { VALUE_RECEIVED; }
    
    /** Get the type of event received.
     * @return The type of event */
    public Type getType();
    
    /** Get the endpoint for which the event was received.
     * @return The endpoint by which the event was generated  */
    public Endpoint<T> getEndpoint();
}
