package me.legrange.panstamp;

/**
 * Event used to notify listeners of events on a gateway. 
 * @author gideon
 */
public interface GatewayEvent {
    
    /** The type of events that can be generated by a gateway */
    public enum Type { DEVICE_DETECTED; }
    
    /** Get the type of the event that occurred. 
     * @return  The type of the event. */
    Type getType();
    
    /** Get the device involved in the event, if there is one
     * @return The device involved in the event.  */
    PanStamp getDevice();
    
}
